# Generated by Django 4.0.4 on 2022-05-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavochki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Долгота')),
                ('y', models.FloatField(verbose_name='Широта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_padik', models.BooleanField(default=False, null=True, verbose_name='Возле подъезда')),
                ('is_ten', models.BooleanField(default=False, null=True, verbose_name='В тени')),
                ('activiti', models.IntegerField(default=1, verbose_name='Активность возле лавочки')),
                ('rating', models.FloatField(default=5.0, null=True, verbose_name='Рейтинг')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='Дата добавление')),
                ('is_valid', models.BooleanField(verbose_name='Проверено')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='media', verbose_name='Фото')),
                ('alt', models.CharField(max_length=250, null=True, verbose_name='Описание')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Проверено')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=250, verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('date_added', models.DateTimeField(verbose_name='Дата добавления')),
                ('lavochka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientside.lavochki', verbose_name='Лавочка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientside.profile', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='lavochki',
            name='photos_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientside.photolav', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='lavochki',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientside.profile', verbose_name='Пользователь'),
        ),
    ]
