# Generated by Django 4.0.4 on 2022-05-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='photos_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientside.photolav', verbose_name='Главное фото'),
        ),
    ]
