# Generated by Django 4.0.4 on 2022-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photolav',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
