# Generated by Django 4.0.4 on 2022-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0002_photolav_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolav',
            name='image_path',
            field=models.ImageField(upload_to='media'),
        ),
    ]
