# Generated by Django 4.0.4 on 2022-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0002_alter_lavochki_photos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavochki',
            old_name='photos_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='lavochki',
            old_name='user_id',
            new_name='user',
        ),
    ]
