# Generated by Django 4.0.4 on 2022-05-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0003_alter_photolav_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='descroption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='photos_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clientside.photolav'),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='raiting',
            field=models.FloatField(blank=True),
        ),
    ]
