# Generated by Django 4.0.4 on 2022-05-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0003_rename_photos_id_lavochki_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='is_padik',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Возле подъезда'),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='is_ten',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='В тени'),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientside.photolav', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='rating',
            field=models.FloatField(blank=True, default=5.0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='photolav',
            name='alt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
