# Generated by Django 4.0.4 on 2022-05-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0006_lavochki_is_activiti_lavochki_is_padik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='photos_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='clientside.photolav'),
        ),
    ]
