# Generated by Django 4.0.4 on 2022-05-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0007_alter_lavochki_photos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientside.profile'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientside.profile'),
        ),
    ]
