# Generated by Django 4.0.4 on 2022-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0008_alter_lavochki_user_id_alter_marks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavochki',
            name='is_ten',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='lavochki',
            name='rating',
            field=models.FloatField(blank=True, default=5.0),
        ),
    ]
